### ISSUE TITLE
XX - Everything is green - XX

### ISSUE THREAD

**Issue by Caballero-Arepa** [Yan-Siv/hexatopia#1]
I have no idea why, but everything has a shade of green. This is a bug of the game, just to let you know that it exists.
![imagen](https://user-images.githubusercontent.com/78449553/182954707-2efabe03-70f0-42ab-885c-6439305c607e.png)

**Comment by Caballero-Arepa** [comment]
Also, I recomend you to set Hexarealm as the fall back tileset

**Comment by Caballero-Arepa** [comment]
Nevermind! Nevermind! I managed to fix the problem.

But seriously tho, make HexaRealm the fallback tileset

**Comment by Yan-Siv** [comment]
> Nevermind! Mevermind! I managed to fix the problem.
> 
> But seriously tho, make HexaRealm the fallback tileset

whats mean 'fallback'?

**Comment by Caballero-Arepa** [comment]
Fallback tileset makes it so the game uses sprites from the specified tileset.

For example, here there are hills missing, as such, the game uses fabtasyhex hills to show something.

So with Hexarealm as fallback, the game would use those hills and it would look a lot better.
